### ISSUE TITLE
Thread no longer kills its children

### ISSUE THREAD

**Issue by mitchellwrosen** [nikita-volkov/slave-thread#7]
Hello Nikita, thank you for the quick patch to address a concern I made in https://github.com/nikita-volkov/slave-thread/issues/5, but I don't think it's quite correct.

Now, it seems a thread will not kill its children if it terminates abnormally. Below is a snippet that demonstrates this:

```haskell
{-# language ScopedTypeVariables #-}

import Control.Concurrent (threadDelay)
import Control.Concurrent.MVar
import Control.Exception
import GHC.Conc (setUncaughtExceptionHandler)
import SlaveThread
import System.IO
import System.IO.Unsafe

main :: IO ()
main = do
  setUncaughtExceptionHandler (say . show)

  fork $ do
    say "[thread 1] spawning thread 2"
    forkFinally
      (say "[thread 2] finalizer")
      (do
        say "[thread 2] sleeping for 1s"
        sleep 1000
        say "[thread 2] bye")
    say "[thread 1] sleeping for 0.5s"
    sleep 500
    say "[thread 1] crashing"
    undefined

  let
    loop =
      sleep 2000 `catch` \(e :: SomeException) -> do
        say "[main] caught exception, sleeping again"
        loop

  loop

sleep ms =
  threadDelay (1000 * ms)

say :: String -> IO ()
say s =
  uninterruptibleMask_ (withMVar lock (\() -> putStrLn s >> hFlush stdout))

lock :: MVar ()
lock = unsafePerformIO (newMVar ())
{-# NOINLINE lock #-}
```

And the output:

```
[thread 1] spawning thread 2
[thread 1] sleeping for 0.5s
[thread 2] sleeping for 1s
[thread 1] crashing
[main] caught exception, sleeping again
[thread 2] bye
[thread 2] finalizer
```

What's going on:

- Thread 1 spawns thread 2
- Thread 2 just hums for a bit
- Meanwhile, thread 1 crashes

Thread 2 is not killed, as evidenced by it printing "bye" and "finalizer".

**Comment by nikita-volkov** [comment]
Right! I guess I know, what's wrong. Would be very helpful, if you PR'd with a test that reproduces the issue. I've migrated the tests to "tasty" instead of "HTF".

Instead of printing, please implement your test's logic using variables. E.g., as I've done in the following transformation of your previous reproduction:
https://github.com/nikita-volkov/slave-thread/blob/f0f5c8fe373d51f9c9d40e48e490918224f4fdbd/test/Main.hs#L18-L37

**Comment by nikita-volkov** [comment]
I've just pushed an attempt to fix this issue to another branch (you can see a commit above). If you do the PR, you can check whether it does fix the issue

**Comment by mitchellwrosen** [comment]
Of course! I've added a stronger test in #10. Above I just demonstrated that a slave is not promptly killed, but the test asserts that the slave's finalizer runs before master. The `fix-#7` branch still fails that test.

**Comment by mitchellwrosen** [comment]
Whoops, I think my test might be broken. Moment... (sorry :sweat_smile:)

**Comment by mitchellwrosen** [comment]
Ok, the test in #10 was fixed by your patch in `fix-#7`!
